---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.6.2

platforms:
  - name: ubuntu-14.04

suites:
  - name: apache
    run_list:
      recipe[django_test::default]
    attributes:
